name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mongoflask101823"
          heroku_email: "herono1692@outlook.com"
          team: "arctix01"
          region: "eu"
          procfile: "web: gunicorn --bind 0.0.0.0:$PORT app:app"
        
          
